#ifndef	ENCH_VERSION_INCLUDED
#define ENCH_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define ENCH_VERSION_MAJOR	2
#define ENCH_VERSION_MINOR	2
#define ENCH_VERSION_PATCH	0
#define ENCH_VERSION_BETA	0
#define ENCH_VERSION_VERSTRING	MAKE_STR(ENCH_VERSION_MAJOR) "." MAKE_STR(ENCH_VERSION_MINOR) "." MAKE_STR(ENCH_VERSION_PATCH) "." MAKE_STR(ENCH_VERSION_BETA)

#endif
