#ifndef	NERR_VERSION_INCLUDED
#define NERR_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define NERR_VERSION_MAJOR	3
#define NERR_VERSION_MINOR	0
#define NERR_VERSION_PATCH	0
#define NERR_VERSION_BETA	0
#define NERR_VERSION_VERSTRING	MAKE_STR(NERR_VERSION_MAJOR) "." MAKE_STR(NERR_VERSION_MINOR) "." MAKE_STR(NERR_VERSION_PATCH) "." MAKE_STR(NERR_VERSION_BETA)

#endif
